### ISSUE TITLE
Sparse BUILD files in googleapis

### ISSUE THREAD

**Issue by Alfus** [google/cel-cpp#12]
The presence of a BUILD file here:
https://github.com/googleapis/googleapis/blob/master/google/api/BUILD.bazel
and not any where in the expr dir, makes it so you can't inject a build file and use the protos.

@TristonianJones @JimLarson

**Comment by kyessenov** [comment]
You can inject a top-level BUILD file but not anywhere within subdirectories (see #13).
I do wonder why googleapis does not provide cc_proto_library out of the box.

**Comment by JimLarson** [comment]
We've added our own BUILD.bazel files.  We should update these as needed instead of injecting them.  Let me know what you'd like to see in them.

**Comment by kyessenov** [comment]
This is fixed upstream as googleapis now provides rules for most languages out-of-the-box.
