### ISSUE TITLE
Not use "TRUE" and "FALSE" for token name?

### ISSUE THREAD

**Issue by didgogns** [google/cel-cpp#121]
It is true that "TRUE" and "FALSE" are not c++ keywords, but many c++ projects use them synonym as `true` and `false`, like
```
//from windef.h
#ifndef FALSE
#define FALSE 0
#endif
#ifndef TRUE
#define TRUE 1
#endif
```
and such projects can create errors when used with cel-cpp.

Therefore, I suggest replacing `TRUE` and `FALSE` in [this grammar file](https://github.com/google/cel-cpp/blob/master/parser/Cel.g4) to something like `CEL_TRUE` and `CEL_FALSE`. How do you think?

**Comment by TristonianJones** [comment]
Hi @didgogns, it's been a while since I looked at the generated source, but I was under the impression that the token names are prefixed and namespaced. Is the current naming causing issues for your build?

**Comment by keith** [comment]
It does appear to cause a build issue in some cases https://github.com/envoyproxy/envoy/issues/18842

I'm still trying to trace back why it broke

**Comment by keith** [comment]
Throwing some more details on the other issue, but since the system appears to define this macro, namespacing doesn't help, since the code I guess just translates to `1 = 1` at compile time. Envoy undefines this for windows, and maybe now will for macos, but I agree with the original intent that it would be nice to avoid these conflicts if possible

**Comment by keith** [comment]
Building with this diff on macOS (with Xcode 13 at least) shows this issue:

```diff
diff --git i/parser/parser_test.cc w/parser/parser_test.cc
index 6bf4204..12d307b 100644
--- i/parser/parser_test.cc
+++ w/parser/parser_test.cc
@@ -1,3 +1,4 @@
+#include <mach/boolean.h>
 #include "parser/parser.h"

 #include <algorithm>
```

**Comment by TristonianJones** [comment]
Thanks for the ping @keith how soon would you need a fix?

**Comment by keith** [comment]
I submitted this PR on envoy to undef these macros right before importing the files here https://github.com/envoyproxy/envoy/pull/18920 so that will likely work fine there for now.

I'm not sure if this is a safe change but I submitted it for discussion https://github.com/google/cel-cpp/pull/134
