### ISSUE TITLE
conformance: divide by zero should be an error

### ISSUE THREAD

**Issue by kyessenov** [google/cel-cpp#19]
Example: `15.75 / 0.0`

Returns: `<double_value:inf >`

Expected: an error

**Comment by kyessenov** [comment]
cc  @JimLarson

**Comment by JimLarson** [comment]
We discussed and we're going with the usual floating-point behavior of having floating point division by zero yield NaN or infinity for zero and nonzero numerator respectively.  We'll update the unit tests accordingly.
