### ISSUE TITLE
feature: provide operator controls for bounded complexity 

### ISSUE THREAD

**Issue by kyessenov** [google/cel-cpp#37]
Add controls for tuning the evaluation cost of the runtime:
**Memory**
Most operations are have no additional allocation costs beyond the memory required to represent the value within the runtime. There are a couple of exceptions to this rule:

Type conversion functions can result in fixed-size allocations, e.g. string to timestamp.
The re2-based matches performs its own allocations when compiling the input regex pattern.
RE2 provides its own internal control for the limits of the regex.
The + operator supports string / list concat where the memory cost is variable with the size of the input.
**CPU**
The majority of CEL functions and macros are O(1) or O(n), with a couple of exceptions.

The re2-based matches is linear, but with a high-constant factor.
The in operator can be super-linear when testing for a string value in a non-literal list.
The comprehension macros all, exists, filter, map support bounded iteration and nesting.

**Tuning**
In many cases, the matches function is eschewed in favor of the simpler startsWith, endsWith, and contains functions.

The in operator can be linted to ensure that a list or map literal appears on the right-hand side of the expression, as this special case is treated as a set membership test rather than as a per-element comparison of the list elements.

Some environments disable the + operator due to its inclusion of string and list overloads. I think that CEL might need to deprecate the concatenation overloads in the near-term in favor of a concat function which can be expressly removed from the environment.

Most of the performance critical use cases for CEL disable macros entirely, though there are a couple of linear-time macros currently supported in Istio.

With the above recommendations, you'll have fixed allocation size operations that run in linear or sub-linear time. If you want to support in and +, I would recommend lint checks on the AST to ensure that they are used in a performance manner (in) or with limited frequency (+).

**Comment by htuch** [comment]
@kyessenov are we going to be able to have these complexity controls on the Envoy RBAC filter now?

**Comment by kyessenov** [comment]
Yeah, need another follow-up to get past -Wunused-parameters build problem. Adding `copts = ["-Wno-unused-parameters"]` doesn't seem to help.
