### ISSUE TITLE
Travis notifications are not posted on PRs

### ISSUE THREAD

**Issue by kyessenov** [google/cel-cpp#62]
See https://github.com/google/cel-cpp/pull/61 for example.
@TristonianJones can you grant me admin access so I can poke around the settings? Or if you have time, can you see why CI integrations is no longer posting notifications.

**Comment by TristonianJones** [comment]
Sure thing. Admin rights have been granted. Welcome back. I was actually thinking of possibly replacing Travis with Cloud Build at some point, but haven't had time to look into it.

**Comment by kyessenov** [comment]
I enabled branch protection. Did you manage to get cloud build triggers set up? I think it wants some project for billing purposes.

**Comment by TristonianJones** [comment]
I looked at the integration guide, but that's as far as I've made it. I can try to get a billing project configured tomorrow morning when I come back on shift.
